# Homebrew formula for the paxel/tap tap — generated by the release workflow,
# which fills in the tagged version and the sha256 of each release tarball and
# pushes the result to the homebrew-tap repository as Formula/dedup.rb.
# Binary formula: it installs the prebuilt `dedup`.
class Dedup < Formula
  desc "Forensic data-inheritance triage: dedupe, diff and browse file piles"
  homepage "https://github.com/paxel/dedup-rs"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/paxel/dedup-rs/releases/download/v0.3.0/dedup-0.3.0-macos-arm64.tar.gz"
      sha256 "3d6bbdf138ac6cff6f47cf546b9c04951316e2d41308658100ee3885252bf870"
    else
      url "https://github.com/paxel/dedup-rs/releases/download/v0.3.0/dedup-0.3.0-macos-x86_64.tar.gz"
      sha256 "319d649e50514db4462a68199d5c458220b3637aed59a715adeac524fadfc52e"
    end
  end

  on_linux do
    url "https://github.com/paxel/dedup-rs/releases/download/v0.3.0/dedup-0.3.0-linux-x86_64.tar.gz"
    sha256 "7e795b0e23ff99d82a615f5cfb6bd859ebae8448d6ddec846a4717464c2366f7"
  end

  def install
    bin.install "dedup"
  end

  def caveats
    <<~EOS
      Optional tools unlock extra features (the app works without them):
        ffmpeg       — video previews, filmstrips, soundtrack playback
        poppler      — PDF page rendering (Render tab)
        libreoffice  — office/legacy document page rendering
    EOS
  end

  test do
    system "#{bin}/dedup", "--help"
  end
end
