# Homebrew formula for the paxel/tap tap — generated by the release workflow,
# which fills in the tagged version and the sha256 of each release tarball and
# pushes the result to the homebrew-tap repository as Formula/dedup.rb.
# Binary formula: it installs the prebuilt `dedup`.
class Dedup < Formula
  desc "Forensic data-inheritance triage: dedupe, diff and browse file piles"
  homepage "https://github.com/paxel/dedup-rs"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/paxel/dedup-rs/releases/download/v0.2.0/dedup-0.2.0-macos-arm64.tar.gz"
      sha256 "888a1531e34d274bede600c80589f9476ca159b2a6d5d496e4f75a75d5d309ac"
    else
      url "https://github.com/paxel/dedup-rs/releases/download/v0.2.0/dedup-0.2.0-macos-x86_64.tar.gz"
      sha256 "72b5deba8da70e638dc5a81bc521b81efc1fcf023bb6c0844c604249d8bd734e"
    end
  end

  on_linux do
    url "https://github.com/paxel/dedup-rs/releases/download/v0.2.0/dedup-0.2.0-linux-x86_64.tar.gz"
    sha256 "545a00f3c96435d0a7ec146411c4529e438c4025f3963e41f20e1ce81c27f2d2"
  end

  def install
    bin.install "dedup"
  end

  def caveats
    <<~EOS
      Optional tools unlock extra features (the app works without them):
        ffmpeg       — video previews, filmstrips, soundtrack playback
        poppler      — PDF page rendering (Render tab)
        libreoffice  — office/legacy document page rendering
    EOS
  end

  test do
    system "#{bin}/dedup", "--help"
  end
end
