# Homebrew formula for the paxel/tap tap — generated by the release workflow,
# which fills in the tagged version and the sha256 of each release tarball and
# pushes the result to the homebrew-tap repository as Formula/dedup.rb.
# Binary formula: it installs the prebuilt `dedup`.
class Dedup < Formula
  desc "Forensic data-inheritance triage: dedupe, diff and browse file piles"
  homepage "https://github.com/paxel/dedup-rs"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/paxel/dedup-rs/releases/download/v0.6.0/dedup-0.6.0-macos-arm64.tar.gz"
      sha256 "c177b73de464b0fc2a74de3e4d7f7a478bcc8f879a23bd28e7407213ddf92561"
    else
      url "https://github.com/paxel/dedup-rs/releases/download/v0.6.0/dedup-0.6.0-macos-x86_64.tar.gz"
      sha256 "d5c48c361df780bc5a31493d2ec86563ce17276c4ef852607abafe218da61dd5"
    end
  end

  on_linux do
    url "https://github.com/paxel/dedup-rs/releases/download/v0.6.0/dedup-0.6.0-linux-x86_64.tar.gz"
    sha256 "6b72b14c9f41898416f92052f30c835a4a2bb3b29aae81aee898f2ea8053b032"
  end

  def install
    bin.install "dedup"
  end

  def caveats
    <<~EOS
      Optional tools unlock extra features (the app works without them):
        ffmpeg       — video previews, filmstrips, soundtrack playback
        poppler      — PDF page rendering (Render tab)
        libreoffice  — office/legacy document page rendering
    EOS
  end

  test do
    system "#{bin}/dedup", "--help"
  end
end
