# Homebrew formula for the paxel/tap tap — generated by the release workflow, which
# fills in the tagged version and the sha256 of each release tarball and pushes the
# result to the homebrew-tap repository as Formula/wiptracker.rb.
# Binary formula: it installs the prebuilt `wiptracker`.
class Wiptracker < Formula
  desc "One-line always-on-top bar showing the task you are focused on right now"
  homepage "https://github.com/paxel/wipTracker"
  version "0.2.0"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/paxel/wipTracker/releases/download/v0.2.0/wiptracker-0.2.0-macos-arm64.tar.gz"
      sha256 "a3aaec54a07cb1b2c3337017aa61f8b8c6a1f1fa278a3525b85c4e1cae705370"
    else
      url "https://github.com/paxel/wipTracker/releases/download/v0.2.0/wiptracker-0.2.0-macos-x86_64.tar.gz"
      sha256 "83c5df8537c16a7aa81213caccec8e10ca6c85484aca03f9be2e74d4bf03eccd"
    end
  end

  on_linux do
    url "https://github.com/paxel/wipTracker/releases/download/v0.2.0/wiptracker-0.2.0-linux-x86_64.tar.gz"
    sha256 "b4c083fe3ea42c5d0c4c86e8a04f9ad991fef3184312885f14138fb58556447d"
  end

  def install
    bin.install "wiptracker"
  end

  def caveats
    <<~EOS
      WipTracker is a desktop bar, not a command-line tool: run `wiptracker` from a
      graphical session. The release also ships WipTracker.app for the Dock; download it
      from the GitHub release page if you prefer that.

      On Wayland the bar cannot stay on top and is started with a window frame, because
      no Wayland protocol exists for either. Use your compositor's own "keep above"
      window rule.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wiptracker --version")
  end
end
